# Generated by Django 3.0.3 on 2020-05-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priec',
            new_name='price',
        ),
    ]
