# Generated by Django 3.0.3 on 2020-05-19 11:14

from django.db import migrations, models
import productapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_auto_20200518_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=productapp.models.upload_image_path),
        ),
    ]
