# Generated by Django 3.0.3 on 2020-05-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_product_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feature',
            new_name='featured',
        ),
    ]
