# Generated by Django 3.0.3 on 2020-05-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0010_auto_20200520_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
